services:
  - type: web
    name: productivitypal
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python discordbot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: REMINDER_CHANNEL_ID
        sync: false
      - key: STATUS_CHANNEL_ID
        sync: false
      - key: JOB_CHANNEL_ID
        sync: false